Parameters:
  VpcName:
    Type: String
    Default: Primary
    AllowedValues:
      - Primary
      - Secondary
    ConstraintDescription: Must be either 'Primary' or 'Secondary'

Conditions:
  IsSecondaryVPC: !Equals [ !Ref VpcName, Secondary ]

Resources:

  RDSInstanceSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub 'rds-subnet-group-${VpcName}'
      DBSubnetGroupDescription: !Sub 'Subnet group for RDS instances in ${VpcName}'
      SubnetIds:
        - !ImportValue !Sub "${VpcName}-Private-Subnets"  # Importing private subnets

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Condition: !Not [ IsSecondaryVPC ]  # Only create if VpcName is not Secondary
    Properties:
      DBInstanceIdentifier: !Sub 'udacity-db-${VpcName}'
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Sub 'udacity${VpcName}'
      MasterUserPassword: !Sub 'udacity${VpcName}!'  # Consider using a secure method
      VPCSecurityGroups:
        - !ImportValue !Sub "${VpcName}-Database-Security-Group"  # Importing database security group
      DBSubnetGroupName: !Ref RDSInstanceSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub 'Udacity ${VpcName} Database'

  StandbyRDSInstance:
    Type: AWS::RDS::DBInstance
    Condition: IsSecondaryVPC
    Properties:
      DBInstanceIdentifier: !Sub 'udacity-db-${VpcName}-standby'
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Sub 'udacity${VpcName}'
      MasterUserPassword: !Sub 'udacity${VpcName}!'  # Consider using a secure method
      VPCSecurityGroups:
        - !ImportValue !Sub "${VpcName}-Database-Security-Group"  # Importing database security group
      DBSubnetGroupName: !Ref RDSInstanceSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub 'Udacity ${VpcName} Standby Database'
      SourceDBInstanceIdentifier: !Ref RDSInstance

Outputs:
  RDSInstance:
    Description: RDS instance ID
    Value: !Ref RDSInstance
  RDSInstanceARN:
    Description: RDS instance ARN
    Value: !GetAtt RDSInstance.Arn
